# Generated by Django 3.1.1 on 2020-10-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postDate',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
