# Generated by Django 3.1.1 on 2020-10-20 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowBlog', '0003_auto_20201020_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postDate',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='Date'),
        ),
    ]
