# Generated by Django 3.1.1 on 2020-12-08 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShowBlog', '0008_auto_20201109_0315'),
    ]

    operations = [
        migrations.RenameField('Post', 'postDate', 'date'),
        migrations.RenameField('Post', 'postTitle', 'title'),
        migrations.RenameField('Post', 'postContent', 'content'),
        migrations.RenameField('Post', 'postImage', 'image'),
        migrations.RenameField('Post', 'postAuthor', 'author'),
        migrations.RenameField('Post', 'postTags', 'tags'),
    ]
