# Generated by Django 3.1.1 on 2020-12-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShowBlog', '0009_auto_20201208_1336'),
    ]

    operations = [
        migrations.RenameField('PostTag', 'tagName', 'name')
    ]
