# Generated by Django 3.1.1 on 2020-12-09 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShowBlog', '0011_auto_20201208_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='pageFilter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='ShowBlog.posttag', verbose_name='Filter Tag'),
        ),
    ]
