# Generated by Django 3.1.1 on 2020-12-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowBlog', '0012_auto_20201209_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='pageFilter',
            new_name='pageTagFilter',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='pageDateFilter',
            field=models.PositiveIntegerField(choices=[(0, 'All'), (1, 'Today'), (7, 'last 7 days'), (30, 'last 30 days'), (90, 'last 90 days'), (365, 'last 365 days')], default=0, help_text='Filter entries older than x days. 0 means no filtering', verbose_name='Filter Date'),
        ),
    ]
