# Generated by Django 3.1.1 on 2020-12-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowBlog', '0014_auto_20201217_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(help_text='Select all the tags this post is related to.', related_name='posts', to='ShowBlog.PostTag', verbose_name='Tags'),
        ),
    ]
