# Generated by Django 3.1.1 on 2020-12-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowBlog', '0015_auto_20201217_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='pageDateFilter',
            field=models.PositiveIntegerField(choices=[(0, 'All'), (1, 'Today'), (7, 'last 7 days'), (30, 'last 30 days'), (90, 'last 90 days'), (180, 'last 180 days'), (365, 'last 365 days')], default=0, help_text='Filter entries older than x days. 0 means no filtering', verbose_name='Filter Date'),
        ),
    ]
