# Generated by Django 3.1.1 on 2020-11-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopage',
            name='infCode',
            field=models.SlugField(blank=True, max_length=20, null=True, verbose_name='Info Page Code'),
        ),
    ]
