# Generated by Django 3.1.1 on 2020-11-02 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ShowInfo', '0002_infopage_infcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopage',
            name='infCode',
            field=models.SlugField(default=django.utils.timezone.now, max_length=20, unique=True, verbose_name='Info Page Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infopage',
            name='infName',
            field=models.CharField(max_length=40, verbose_name='Info Page Name'),
        ),
    ]
