# Generated by Django 3.1.1 on 2020-11-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowInfo', '0008_infopage_inflinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopage',
            name='infLinks',
            field=models.ManyToManyField(blank=True, to='ShowInfo.InfoPage', verbose_name='Additional Info Links'),
        ),
    ]
