# Generated by Django 3.1.1 on 2020-11-08 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShowInfo', '0010_infooption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoOption',
        ),
    ]
