# Generated by Django 3.1.1 on 2020-11-09 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShowInfo', '0011_delete_infooption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoPage',
        ),
    ]
