# Generated by Django 3.1.1 on 2020-11-09 00:53

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '0018_auto_20201108_2153'),
        ('ShowInfo', '0012_delete_infopage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainApp.page')),
                ('infText', tinymce.models.HTMLField()),
            ],
            bases=('mainApp.page',),
        ),
    ]
