# Generated by Django 3.1.1 on 2020-11-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowInfo', '0013_infopage'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopage',
            name='infLinks',
            field=models.ManyToManyField(blank=True, related_name='_infopage_infLinks_+', to='ShowInfo.InfoPage', verbose_name='Additional Info Links'),
        ),
    ]
