# Generated by Django 3.1.1 on 2020-12-17 22:59

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowInfo', '0014_infopage_inflinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopage',
            name='infLinks',
            field=models.ManyToManyField(blank=True, help_text='Select (optional) all the info pages you want to be accessed directly from this one.', related_name='_infopage_infLinks_+', to='ShowInfo.InfoPage', verbose_name='Additional Info Links'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='infText',
            field=tinymce.models.HTMLField(help_text='Enter the text info to be displayed in this page / menu option', verbose_name='Text'),
        ),
    ]
