# Generated by Django 3.1.1 on 2020-10-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optOrder', models.CharField(max_length=10, unique=True, verbose_name='Order')),
                ('optEnabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('optName', models.CharField(max_length=30, verbose_name='Option Name')),
                ('optType', models.CharField(choices=[('HOM', 'Home'), ('INF', 'ShowInfo'), ('BLG', 'ShowBlog'), ('CON', 'ShowContact'), ('ITM', 'ShowItems')], default='INF', max_length=3, verbose_name='Option Type')),
                ('optParameter', models.CharField(blank=True, max_length=60, verbose_name='Aditional Parameter')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'menu option',
                'verbose_name_plural': 'menu options',
            },
        ),
    ]
