# Generated by Django 3.1.1 on 2020-10-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuoption',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
