# Generated by Django 3.1.1 on 2020-10-29 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20201019_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styleName', models.CharField(max_length=20, unique=True, verbose_name='Style Name')),
                ('styleBGColor', models.CharField(blank=True, max_length=100, verbose_name='Background color')),
                ('styleBGImage', models.ImageField(blank=True, null=True, upload_to='mainApp', verbose_name='Background Image')),
                ('styleTextColor', models.CharField(blank=True, max_length=100, verbose_name='Text color')),
                ('styleInfoBoxColor', models.CharField(blank=True, max_length=100, verbose_name='Text color')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'style',
                'verbose_name_plural': 'styles',
            },
        ),
        migrations.AddField(
            model_name='menuoption',
            name='optImageTitle',
            field=models.ImageField(blank=True, null=True, upload_to='mainApp', verbose_name='Image title'),
        ),
        migrations.AddField(
            model_name='menuoption',
            name='optMainTitle',
            field=models.CharField(blank=True, max_length=60, verbose_name='Main title'),
        ),
        migrations.AddField(
            model_name='menuoption',
            name='optStyle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.style', verbose_name='Style'),
        ),
    ]
