# Generated by Django 3.1.1 on 2020-10-29 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20201029_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuoption',
            name='optStyle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.style', verbose_name='Style'),
        ),
    ]
