# Generated by Django 3.1.1 on 2020-10-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20201029_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuoption',
            name='optMainTitle',
            field=models.CharField(max_length=60, verbose_name='Main title'),
        ),
    ]
