# Generated by Django 3.1.1 on 2020-10-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20201029_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='styleBGColor',
            field=models.CharField(blank=True, max_length=120, verbose_name='Background color'),
        ),
        migrations.AlterField(
            model_name='style',
            name='styleInfoBoxColor',
            field=models.CharField(blank=True, max_length=120, verbose_name='Info box color'),
        ),
        migrations.AlterField(
            model_name='style',
            name='styleTextBGColor',
            field=models.CharField(blank=True, max_length=120, verbose_name='Text BG color'),
        ),
        migrations.AlterField(
            model_name='style',
            name='styleTextColor',
            field=models.CharField(blank=True, max_length=120, verbose_name='Text color'),
        ),
    ]
