# Generated by Django 3.1.1 on 2020-10-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20201030_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuoption',
            name='optParameter',
            field=models.CharField(blank=True, max_length=120, verbose_name='Aditional Parameter'),
        ),
    ]
