# Generated by Django 3.1.1 on 2020-10-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20201031_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuoption',
            name='optOrder',
            field=models.SlugField(max_length=10, unique=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='style',
            name='styleName',
            field=models.SlugField(max_length=20, unique=True, verbose_name='Style Name'),
        ),
    ]
