# Generated by Django 3.1.1 on 2020-11-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20201102_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuoption',
            name='optApp',
            field=models.CharField(choices=[('HOM', 'Home'), ('INF', 'ShowInfo'), ('BLG', 'ShowBlog'), ('CON', 'ShowContact'), ('ITM', 'ShowItems')], default='INF', max_length=3, verbose_name='Option Type'),
        ),
    ]
