# Generated by Django 3.1.1 on 2020-11-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_menuoption_optapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuoption',
            name='optType',
        ),
        migrations.AlterField(
            model_name='menuoption',
            name='optApp',
            field=models.CharField(choices=[('HOM', 'Home'), ('INF', 'ShowInfo'), ('BLG', 'ShowBlog'), ('CON', 'ShowContact'), ('ITM', 'ShowItems')], default='INF', max_length=3, verbose_name='Option App'),
        ),
    ]
