# Generated by Django 3.1.1 on 2020-11-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_auto_20201104_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuoption',
            name='optType',
            field=models.CharField(choices=[('NAVBAR', 'NAVBAR'), ('FOOTER', 'FOOTER')], default='NAVBAR', max_length=6, verbose_name='Option Type'),
        ),
    ]
