# Generated by Django 3.1.1 on 2020-11-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_menuoption_opttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuoption',
            name='optNavBar',
        ),
        migrations.AlterField(
            model_name='menuoption',
            name='optType',
            field=models.CharField(choices=[('NAVBAR', 'NavBar'), ('FOOTER', 'Footer')], default='NAVBAR', max_length=6, verbose_name='Option Type'),
        ),
    ]
