# Generated by Django 3.1.1 on 2020-11-08 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShowItems', '0005_delete_itemsoption'),
        ('ShowInfo', '0011_delete_infooption'),
        ('mainApp', '0015_option'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
    ]
