# Generated by Django 3.1.1 on 2020-11-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='location',
            field=models.CharField(blank=True, choices=[('NAVBAR', 'NavBar'), ('FOOTER', 'Footer')], default='NAVBAR', max_length=6, verbose_name='Location'),
        ),
    ]
