# Generated by Django 3.1.1 on 2020-11-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='app',
            field=models.CharField(choices=[('HOM', 'Home'), ('INF', 'ShowInfo'), ('BLG', 'ShowBlog'), ('CON', 'ShowContact'), ('ITM', 'ShowItems')], max_length=3, verbose_name='Option App'),
        ),
        migrations.AlterField(
            model_name='page',
            name='location',
            field=models.CharField(blank=True, choices=[('NAVBAR', 'NavBar'), ('FOOTER', 'Footer')], max_length=6, verbose_name='Location'),
        ),
    ]
