# Generated by Django 3.1.1 on 2020-11-10 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_auto_20201109_0349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuOption',
        ),
    ]
