# Generated by Django 3.1.1 on 2020-11-15 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0022_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prueba',
        ),
    ]
