# Generated by Django 3.1.1 on 2020-11-21 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0024_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
