# Generated by Django 3.1.1 on 2020-11-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0025_delete_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='homeImage',
            field=models.ImageField(blank=True, null=True, upload_to='mainApp', verbose_name='Home Page Image'),
        ),
    ]
