# Generated by Django 3.1.1 on 2020-11-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0026_page_homeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailHost', models.CharField(blank=True, default='', max_length=100)),
                ('emailHostUser', models.CharField(blank=True, default='', max_length=100)),
                ('emailHostPassword', models.CharField(blank=True, default='', max_length=50)),
                ('emailPort', models.PositiveIntegerField(blank=True, default=587)),
                ('emailUseTLS', models.BooleanField()),
                ('emailUseSSL', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
