# Generated by Django 3.1.1 on 2020-11-28 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0027_sitesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
