# Generated by Django 3.1.1 on 2020-11-28 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0029_sitesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
