# Generated by Django 3.1.1 on 2020-12-09 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0034_auto_20201209_0018'),
    ]

    operations = [
        migrations.RenameField('Style', 'styleName', 'name'),        
        migrations.RenameField('Style', 'styleBGColor', 'bgColor'),     
        migrations.RenameField('Style', 'styleBGImage', 'bgImage'),     
        migrations.RenameField('Style', 'styleTextColor', 'textColor'),   
        migrations.RenameField('Style', 'styleTextBGColor', 'textBGColor'), 
        migrations.RenameField('Style', 'styleInfoBoxColor', 'infoBoxColor'),
    ]
