# Generated by Django 3.1.1 on 2020-12-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0035_auto_20201209_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='emailUseTLS',
            field=models.BooleanField(default=True, verbose_name='Email Use TLS'),
        ),
    ]
