# Generated by Django 3.1.1 on 2020-12-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0037_auto_20201217_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cartExpiryTime',
            field=models.PositiveIntegerField(default=15, verbose_name='Shopping Carts expiry time (in days)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='homeImage',
            field=models.ImageField(blank=True, help_text='Upload an image that will link to this menu option in the home page (optional)', null=True, upload_to='mainApp', verbose_name='Home Page Image'),
        ),
    ]
