# Generated by Django 3.1.1 on 2020-12-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0039_sitesettings_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='language',
            new_name='siteLanguage',
        ),
    ]
