# Generated by Django 3.1.1 on 2020-10-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowItems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemDescrip',
            field=models.CharField(blank=True, max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemImage',
            field=models.ImageField(blank=True, null=True, upload_to='ShowItems', verbose_name='Image (big)'),
        ),
    ]
