# Generated by Django 3.1.1 on 2020-10-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowItems', '0002_auto_20201025_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemDescrip',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.CharField(max_length=60, verbose_name='Name'),
        ),
    ]
