# Generated by Django 3.1.1 on 2020-11-07 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_option'),
        ('ShowItems', '0003_auto_20201031_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsOption',
            fields=[
                ('option_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainApp.option')),
                ('categories', models.ManyToManyField(to='ShowItems.ItemCategory', verbose_name='Categories')),
            ],
            bases=('mainApp.option',),
        ),
    ]
