# Generated by Django 3.1.1 on 2020-11-09 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_auto_20201108_2153'),
        ('ShowItems', '0005_delete_itemsoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainApp.page')),
                ('pageFilter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ShowItems.itemcategory', verbose_name='Filter Category')),
            ],
            bases=('mainApp.page',),
        ),
    ]
