# Generated by Django 3.1.1 on 2020-11-28 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShowContact', '0012_contactpage_showsocialmedia'),
        ('ShowItems', '0009_auto_20201123_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemspage',
            name='sendCartPage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ShowContact.contactpage', verbose_name='Send Cart Page'),
        ),
    ]
