# Generated by Django 3.1.1 on 2020-11-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowItems', '0010_itemspage_sendcartpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
