# Generated by Django 3.1.1 on 2020-11-30 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShowItems', '0011_auto_20201128_2111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
