# Generated by Django 3.1.1 on 2020-11-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowItems', '0013_auto_20201130_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
