# Generated by Django 3.1.1 on 2020-12-06 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShowItems', '0014_auto_20201130_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='items',
        ),
    ]
