# Generated by Django 3.1.1 on 2020-12-06 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShowItems', '0015_remove_shoppingcart_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemCartRelationship',
        ),
    ]
