# Generated by Django 3.1.1 on 2020-12-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowItems', '0016_delete_itemcartrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='items',
            field=models.ManyToManyField(to='ShowItems.Item'),
        ),
    ]
