# Generated by Django 3.1.1 on 2020-12-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShowItems', '0017_shoppingcart_items'),
    ]

    operations = [
        migrations.RenameField('ItemCategory', 'catName', 'name'),
        migrations.RenameField('Item', 'itemCode', 'code'),
        migrations.RenameField('Item', 'itemName', 'name'),
        migrations.RenameField('Item', 'itemDescrip', 'descrip'),
        migrations.RenameField('Item', 'itemThumb', 'thumb'),
        migrations.RenameField('Item', 'itemImage', 'image'),
        migrations.RenameField('Item', 'itemCats', 'categs'),
    ]
