# Generated by Django 3.1.1 on 2020-12-09 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShowContact', '0012_contactpage_showsocialmedia'),
        ('ShowItems', '0018_auto_20201208_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categs',
            field=models.ManyToManyField(related_name='items', to='ShowItems.ItemCategory', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='itemspage',
            name='pageFilter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='ShowItems.itemcategory', verbose_name='Filter Category'),
        ),
        migrations.AlterField(
            model_name='itemspage',
            name='sendCartPage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemPages', to='ShowContact.contactpage', verbose_name='Send Cart Page'),
        ),
    ]
