# Generated by Django 3.1.1 on 2020-12-10 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShowItems', '0019_auto_20201209_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemspage',
            old_name='pageFilter',
            new_name='pageCatFilter',
        ),
    ]
