# Generated by Django 3.1.1 on 2020-12-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowItems', '0021_auto_20201217_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='items',
            field=models.ManyToManyField(help_text='The items list of the Cart', related_name='ShoppingCarts', to='ShowItems.Item'),
        ),
    ]
