# Generated by Django 3.1.1 on 2020-11-25 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShowContact', '0003_auto_20201124_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SlugField(max_length=10, unique=True, verbose_name='Order')),
                ('profileName', models.CharField(max_length=50, verbose_name='Profile name')),
                ('profileLink', models.URLField(verbose_name='Profile link')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialMedia', models.CharField(max_length=50, unique=True, verbose_name='Social media')),
            ],
        ),
        migrations.DeleteModel(
            name='ContactChannel',
        ),
        migrations.AlterModelOptions(
            name='mailto',
            options={'verbose_name': 'Mail recipient', 'verbose_name_plural': 'Mail recipients'},
        ),
        migrations.AlterModelOptions(
            name='subjectoption',
            options={'verbose_name': 'Mail subject', 'verbose_name_plural': 'Mail subjects'},
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='socialMedia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShowContact.socialmediaoptions', verbose_name='Social media'),
        ),
    ]
