# Generated by Django 3.1.1 on 2020-11-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowContact', '0004_auto_20201125_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': "Company's social media", 'verbose_name_plural': "Company's social media"},
        ),
        migrations.AlterModelOptions(
            name='socialmediaoptions',
            options={'verbose_name': 'Social media option', 'verbose_name_plural': 'Social media options'},
        ),
        migrations.AddField(
            model_name='socialmediaoptions',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Social media'),
        ),
    ]
