# Generated by Django 3.1.1 on 2020-11-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowContact', '0005_auto_20201125_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Social media')),
            ],
            options={
                'verbose_name': 'Social media option',
                'verbose_name_plural': 'Social media options',
            },
        ),
    ]
