# Generated by Django 3.1.1 on 2020-11-25 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShowContact', '0006_socialmediaoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='socialMedia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShowContact.socialmediaoption', verbose_name='Social media'),
        ),
        migrations.DeleteModel(
            name='SocialMediaOptions',
        ),
    ]
