# Generated by Django 3.1.1 on 2020-11-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowContact', '0008_auto_20201126_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailhostconfig',
            name='id',
            field=models.AutoField(auto_created=True, default=33, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailhostconfig',
            name='configId',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
