# Generated by Django 3.1.1 on 2020-11-28 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShowContact', '0010_auto_20201126_1052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailHostConfig',
        ),
    ]
