# Generated by Django 3.1.1 on 2020-12-17 22:59

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowContact', '0012_contactpage_showsocialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='enableShopCart',
            field=models.BooleanField(default=False, help_text='Display the shopping cart and let the user attach it to an email', verbose_name='Enable Shopping Cart'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='showSocialMedia',
            field=models.BooleanField(default=False, help_text='Show the social media of the company', verbose_name='Show Social Media'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='text_1',
            field=tinymce.models.HTMLField(blank=True, help_text='This text will be displayed before the email fields', null=True, verbose_name='Text 1'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='text_2',
            field=tinymce.models.HTMLField(blank=True, help_text='This text will be displayed before Shopping Cart related fields', null=True, verbose_name='Text 2'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='text_3',
            field=tinymce.models.HTMLField(blank=True, help_text='This text will be displayed at the end of the page, you can put here some not social media contact info, ie: phone number, address, etc.', null=True, verbose_name='Text 3'),
        ),
        migrations.AlterField(
            model_name='mailto',
            name='address',
            field=models.EmailField(help_text='Enter an email address in your company, where you want the users be able to send their inquiries', max_length=100, unique=True, verbose_name='Mail Address'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='order',
            field=models.SlugField(help_text='The social media will be displayed ordered by this field, but this field itself will not be displayed', max_length=10, unique=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='profileLink',
            field=models.URLField(help_text='Enter an URL so the user can click and access directly to your profile', verbose_name='Profile link'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='profileName',
            field=models.CharField(help_text="Enter your company's profile name for this social media", max_length=50, verbose_name='Profile name'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='socialMedia',
            field=models.ForeignKey(help_text='Select a social media from the list', on_delete=django.db.models.deletion.CASCADE, to='ShowContact.socialmediaoption', verbose_name='Social media'),
        ),
        migrations.AlterField(
            model_name='socialmediaoption',
            name='code',
            field=models.CharField(help_text='Code to display the social media icon', max_length=50, unique=True, verbose_name='Social media code'),
        ),
        migrations.AlterField(
            model_name='subjectoption',
            name='subject',
            field=models.CharField(help_text="Enter a possible subject for the user's email", max_length=100, unique=True, verbose_name='Subject'),
        ),
    ]
